%% ISD nifti vs. Josh nifti-from-mrecon comparison
%
% Josh creates nifti files in his mrecon toolbox from the MRecon objects
% - Want to compare the srow information output by the scanner vs. his
% output
% - use flow_phantom_6 dataset
%
% see readme for results: basically Josh puts into correct world system,
% but internal nifti is slightly different to .nii generated by ISDPACS
%

sp_josh_original = 'C:\Users\tr17\Documents\Projects\PC_Fetal_CMR\Data\2018_11_01_Flow_Phantom6\PC-bSSFP';
cd(sp_josh_original);
sp = sp_josh_original;

% sp_josh_corrected = 'C:\Users\tr17\Documents\Projects\PC_Fetal_CMR\Data\2018_11_01_Flow_Phantom6\PC-bSSFP_recon_2018_11_01_nifti_affine_correction';
% cd(sp_josh_corrected);
% sp = sp_josh_corrected;


%% load ISDPACS nifti files
%- downloaded straight from ISDPACs

sp_isd = 'C:\Users\tr17\Documents\Projects\PC_Fetal_CMR\Data\2018_11_01_Flow_Phantom6\PC-bSSFP\nii_isdpacs';
cd(sp_isd);

[isd1,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3001_PIH1bffeM2D_Mplus_axCLEAR'); isd.tra.p.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3101_PIH1bffeM2D_Mplus_sagCLEAR'); isd.sag.p.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3201_PIH1bffeM2D_Mplus_corCLEAR'); isd.cor.p.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3601_PIH1bffeM2D_Mminus_ax_Experiment1CLEAR'); isd.tra.m.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3701_PIH1bffeM2D_Mminus_sag_Experiment1CLEAR'); isd.sag.m.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3801_PIH1bffeM2D_Mminus_cor_Experiment1CLEAR'); isd.cor.m.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3301_PIH1bffeM2D_Mplus_ax_rotAP45CLEAR'); isd.tra.o.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3401_PIH1bffeM2D_Mplus_sag_rotRL45CLEAR'); isd.sag.o.hdr = hdr;
[~,hdr] = efon('201811011814_PHILIPSJ2LF9B9_3501_PIH1bffeM2D_Mplus_cor_rotAP45CLEAR'); isd.cor.o.hdr = hdr;


%% load Josh mrecon toolbox generated nifti files
%- mrecon run on .raw files using classical approach
%- nifti files generated using: mrecon_writenifti.m

cd(sp);

% M+
scanName{1} = 'fl_01112018_2023463_30_2_pih1bffem2dmplusaxclearV4';
scanName{2} = 'fl_01112018_2029121_31_2_pih1bffem2dmplussagclearV4';
scanName{3} = 'fl_01112018_2031445_32_2_pih1bffem2dmpluscorclearV4';

% M-
scanName{4} = 'fl_01112018_2057445_36_2_pih1bffem2dmminusaxexperiment1clearV4';
scanName{5} = 'fl_01112018_2102065_37_2_pih1bffem2dmminussagexperiment1clearV4';
scanName{6} = 'fl_01112018_2105508_38_2_pih1bffem2dmminuscorexperiment1clearV4';

% Oblique
scanName{7} = 'fl_01112018_2042459_33_2_pih1bffem2dmplusaxrotap45clearV4';
scanName{8} = 'fl_01112018_2048374_34_2_pih1bffem2dmplussagrotrl45clearV4';
scanName{9} = 'fl_01112018_2050360_35_2_pih1bffem2dmpluscorrotap45clearV4';


nii = load_untouch_nii([scanName{1} '_MAG.nii.gz']); mrecon.tra.p.hdr = nii.hdr;
nii = load_untouch_nii([scanName{2} '_MAG.nii.gz']); mrecon.sag.p.hdr = nii.hdr;
nii = load_untouch_nii([scanName{3} '_MAG.nii.gz']); mrecon.cor.p.hdr = nii.hdr;
nii = load_untouch_nii([scanName{4} '_MAG.nii.gz']); mrecon.tra.m.hdr = nii.hdr;
nii = load_untouch_nii([scanName{5} '_MAG.nii.gz']); mrecon.sag.m.hdr = nii.hdr;
nii = load_untouch_nii([scanName{6} '_MAG.nii.gz']); mrecon.cor.m.hdr = nii.hdr;
nii = load_untouch_nii([scanName{7} '_MAG.nii.gz']); mrecon.tra.o.hdr = nii.hdr;
nii = load_untouch_nii([scanName{8} '_MAG.nii.gz']); mrecon.sag.o.hdr = nii.hdr;
nii = load_untouch_nii([scanName{9} '_MAG.nii.gz']); mrecon.cor.o.hdr = nii.hdr;


%% srow comparisons:

[S_isd.tra.p, S_mrecon.tra.p]=srow_compare(isd.tra.p.hdr.hist,mrecon.tra.p.hdr.hist);
[S_isd.sag.p, S_mrecon.sag.p]=srow_compare(isd.sag.p.hdr.hist,mrecon.sag.p.hdr.hist);
[S_isd.cor.p, S_mrecon.cor.p]=srow_compare(isd.cor.p.hdr.hist,mrecon.cor.p.hdr.hist);
[S_isd.tra.m, S_mrecon.tra.m]=srow_compare(isd.tra.m.hdr.hist,mrecon.tra.m.hdr.hist);
[S_isd.sag.m, S_mrecon.sag.m]=srow_compare(isd.sag.m.hdr.hist,mrecon.sag.m.hdr.hist);
[S_isd.cor.m, S_mrecon.cor.m]=srow_compare(isd.cor.m.hdr.hist,mrecon.cor.m.hdr.hist);
[S_isd.tra.o, S_mrecon.tra.o]=srow_compare(isd.tra.o.hdr.hist,mrecon.tra.o.hdr.hist);
[S_isd.sag.o, S_mrecon.sag.o]=srow_compare(isd.sag.o.hdr.hist,mrecon.sag.o.hdr.hist);
[S_isd.cor.o, S_mrecon.cor.o]=srow_compare(isd.cor.o.hdr.hist,mrecon.cor.o.hdr.hist);



function [S_isd, S_mrecon]=srow_compare(hist_isd,hist_mrecon)

    S_isd = [hist_isd.srow_x; hist_isd.srow_y; hist_isd.srow_z];
    S_mrecon = [hist_mrecon.srow_x; hist_mrecon.srow_y; hist_mrecon.srow_z];

end

