function [L, T] = O_matrix2niiLattice(O_matrix)

% function to transform O_matrix taken from goalc code into same
% orientation as Image Lattice in .nii file

% worked out using "mirtk info" and comparing to an O_matrix from goalc
% file

% T = transformation from Philips coordinates to nifti coordinates
% nb: nifti coordinates based on .nii generated by Josh in fcmr mrecon code
% This should be LR-PA-FH

T = [-1 0 0; ...
     0 -1 0; ...
     0 0 1];
 
L = T * [O_matrix(:,2), O_matrix(:,1), O_matrix(:,3)];


end